### ISSUE TITLE
AxiosError: Request failed with status code 429

### ISSUE THREAD

**Issue by sirEgghead** [AidanWelch/google-translate-api#12]
We were doing fine until this morning.  It seems that we have now reached a rate limit on the API key.

![image](https://user-images.githubusercontent.com/6648625/186951558-426d2c4b-0ae1-4379-bea5-061c06e55156.png)

**Comment by sirEgghead** [comment]
Also, thank you for this fork!

**Comment by AidanWelch** [comment]
> We were doing fine until this morning. It seems that we have now reached a rate limit on the API key.

You're actually not using an API key, instead this package simply is using the public Google Translate endpoints, so what probably happened is Google rate limited just because of the number of requests from your IP, you may benefit from using a proxy.

[v10.4.0](https://github.com/AidanWelch/google-translate-api/releases/tag/v10.4.0) supports batch translations in a single request, so you should be to batch what you need translated together and keep requests down.  Also, it is probably not only an issue of number of requests but spacing between them, if you are doing a lot of requests you may want to add a delay between them instead of sending them all at once.

**Comment by sirEgghead** [comment]
I assumed the package was using an API key since it's Google Translate.

My app personally isn't hitting the Google rate limit, as there are less than 20 requests per day.

**Comment by AidanWelch** [comment]
Moving to [#16]
