### ISSUE TITLE
how can I change text direction from ltr to rtl ?

### ISSUE THREAD

**Issue by shayan-developer** [AidanWelch/google-translate-api#15]

**Comment by AidanWelch** [comment]
Related to [vitalets#13](https://github.com/vitalets/google-translate-api/issues/13)

Can you provide an example of you're problem that I can experiment on though?

**Comment by shayan-developer** [comment]
For example, I want to translate this text to persian (fa)
'and building restful and even graphQL APIs, working with real time data and web sockets and much',

and this is response 
'و ساختن API های آرامش بخش و حتی GraphQL ، کار با داده های زمان واقعی و سوکت های وب و چیزهای زیادی '

Here the text is messed up because it's not RTL (right to left direction)
@AidanWelch

**Comment by AidanWelch** [comment]
Hmm, so this is a weird error, because is very much environment dependent 

و ساختن API های آرامش بخش و حتی GraphQL ، کار با داده های زمان واقعی و سوکت های وب و چیزهای زیادی

Here I translated then just copied from console.log which printed it LTR but Github perhaps has correctly recognized it as RTL.  I guess it depends on your circumstance, but if it is in browser maybe just using `<p dir="rtl"> ... </p>` would help.  As mentioned in [vitalets#13](https://github.com/vitalets/google-translate-api/issues/13) it is still permitted.

Sorry I can't help more.
