### ISSUE TITLE
 ERROR  [TypeError: Cannot convert null value to object]

### ISSUE THREAD

**Issue by MertCelik0** [AidanWelch/google-translate-api#31]
Hello, I am getting the error in the title while translating text. I suspected it because I was using texts dynamically. Then I tried to translate the texts statically but this error returns 1 time out of 5 translations (same text).

**Comment by AidanWelch** [comment]
Hi, can you please send the full error?

Also make sure you are updated to the latest version because there was an update that addressed a possible cause of the error.  Other than that it is likely the error is caused by either a network error, or a rate limit.  I will try to implement more descriptive error checking for that

**Comment by MertCelik0** [comment]
Sorry for not responding quickly.
Here is the error I got.
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-15 at 20 27 03](https://github.com/AidanWelch/google-translate-api/assets/90933876/a188e546-b29e-45fb-a76c-b2cc3e0aba9c)
